author: Gozzilioni
url: odraccir.github.com
permalink: pretty
paginate: 20

markdown: maruku


exclude: start_jeckyll.bat
prod_build: false

plugins: ./_plugins
destination: ./_sites
category_dir: ./_category